//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceLM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shoppingcart
    {
        public int ShopCartID { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<bool> OrderClient { get; set; }
        public Nullable<int> Users { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
